#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER docker;
    CREATE USER "$CYCLOPS_USER";
    CREATE DATABASE docker;
    GRANT ALL PRIVILEGES ON DATABASE docker TO docker;
    CREATE DATABASE "$POSTGRES_DB1";
    CREATE DATABASE "$POSTGRES_DB2";
    CREATE DATABASE "$POSTGRES_DB3";
    CREATE DATABASE "$POSTGRES_DB4";
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB1" TO "$CYCLOPS_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB2" TO "$CYCLOPS_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB3" TO "$CYCLOPS_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB4" TO "$CYCLOPS_USER";
EOSQL
